//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema
{
    using System.Linq;
    using System.Runtime.Serialization;


    public class Animation
    {

        /// <summary>
        /// Backing field for channels.
        /// </summary>
        private AnimationChannel[] m_channels;

        /// <summary>
        /// Backing field for samplers.
        /// </summary>
        private AnimationSampler[] m_samplers;

        /// <summary>
        /// Backing field for the Name.
        /// </summary>
        private string m_name;

        /// <summary>
        /// Backing field for the Extensions property.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> m_extensions;

        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras m_extras;

        /// <summary>
        /// An array of channels, each targeting an animation's sampler at a node's property. Different channels of the same animation can't have the same targets.
        /// </summary>
        [Newtonsoft.Json.JsonRequiredAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("channels")]
        public AnimationChannel[] Channels
        {
            get
            {
                return this.m_channels;
            }
            set
            {
                this.m_channels = value;
            }
        }

        /// <summary>
        /// An array of samplers that combine input and output accessors with an interpolation algorithm to define a keyframe graph (but not its target).
        /// </summary>
        [Newtonsoft.Json.JsonRequiredAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("samplers")]
        public AnimationSampler[] Samplers
        {
            get
            {
                return this.m_samplers;
            }
            set
            {
                this.m_samplers = value;
            }
        }

        /// <summary>
        /// The user-defined name for this object.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        public string Name
        {
            get
            {
                return this.m_name;
            }
            set
            {
                this.m_name = value;
            }
        }

        /// <summary>
        /// Dictionary object containing extension-specific items.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this.m_extensions;
            }
            set
            {
                this.m_extensions = value;
            }
        }

        /// <summary>
        /// Application-specific information.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this.m_extras;
            }
            set
            {
                this.m_extras = value;
            }
        }

        public bool ShouldSerializeChannels()
        {
            return ((m_channels == null)
                        == false);
        }

        public bool ShouldSerializeSamplers()
        {
            return ((m_samplers == null)
                        == false);
        }

        public bool ShouldSerializeName()
        {
            return ((m_name == null)
                        == false);
        }

        public bool ShouldSerializeExtensions()
        {
            return ((m_extensions == null)
                        == false);
        }

        public bool ShouldSerializeExtras()
        {
            return ((m_extras == null)
                        == false);
        }
    }
}
