//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glTFLoader.Schema
{
    using Evergine.Mathematics;
    using System.Linq;
    using System.Runtime.Serialization;


    public class MaterialPbrMetallicRoughness
    {

        /// <summary>
        /// Backing field for the BaseColorFactor.
        /// </summary>
        private float[] m_baseColorFactor = new float[] {
                1F,
                1F,
                1F,
                1F};

        /// <summary>
        /// Backing field for the BaseColorTexture.
        /// </summary>
        private TextureInfo m_baseColorTexture;

        /// <summary>
        /// Backing field for the MetallicFactor.
        /// </summary>
        private float m_metallicFactor = 1F;

        /// <summary>
        /// Backing field for the RoughnessFactor.
        /// </summary>
        private float m_roughnessFactor = 1F;

        /// <summary>
        /// Backing field for the MetallicRoughnessTexture.
        /// </summary>
        private TextureInfo m_metallicRoughnessTexture;

        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> m_extensions;

        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras m_extras;

        /// <summary>
        /// The base color factor of the material.
        /// </summary>
        [Newtonsoft.Json.JsonConverterAttribute(typeof(glTFLoader.Shared.ArrayConverter))]
        [Newtonsoft.Json.JsonPropertyAttribute("baseColorFactor")]
        public float[] BaseColorFactor
        {
            get
            {
                return this.m_baseColorFactor;
            }
            set
            {
                if ((value.Length < 4u))
                {
                    throw new System.ArgumentException("Array not long enough");
                }
                if ((value.Length > 4u))
                {
                    throw new System.ArgumentException("Array too long");
                }
                int index = 0;
                for (index = 0; (index < value.Length); index = (index + 1))
                {
                    value[index] = MathHelper.Clamp(value[index], 0, 1);
                }

                this.m_baseColorFactor = value;
            }
        }

        /// <summary>
        /// The base color texture.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("baseColorTexture")]
        public TextureInfo BaseColorTexture
        {
            get
            {
                return this.m_baseColorTexture;
            }
            set
            {
                this.m_baseColorTexture = value;
            }
        }

        /// <summary>
        /// The metallicity of the material.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("metallicFactor")]
        public float MetallicFactor
        {
            get
            {
                return this.m_metallicFactor;
            }
            set
            {
                value = MathHelper.Clamp(value, 0, 1);
                this.m_metallicFactor = value;
            }
        }

        /// <summary>
        /// The roughness of the material.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("roughnessFactor")]
        public float RoughnessFactor
        {
            get
            {
                return this.m_roughnessFactor;
            }
            set
            {
                value = MathHelper.Clamp(value, 0, 1);
                this.m_roughnessFactor = value;
            }
        }

        /// <summary>
        /// The metallic-roughness texture.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("metallicRoughnessTexture")]
        public TextureInfo MetallicRoughnessTexture
        {
            get
            {
                return this.m_metallicRoughnessTexture;
            }
            set
            {
                this.m_metallicRoughnessTexture = value;
            }
        }

        /// <summary>
        /// Dictionary object containing extension-specific objects.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this.m_extensions;
            }
            set
            {
                this.m_extensions = value;
            }
        }

        /// <summary>
        /// Application-specific data.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this.m_extras;
            }
            set
            {
                this.m_extras = value;
            }
        }

        public bool ShouldSerializeBaseColorFactor()
        {
            return (m_baseColorFactor.SequenceEqual(new float[] {
                        1F,
                        1F,
                        1F,
                        1F}) == false);
        }

        public bool ShouldSerializeBaseColorTexture()
        {
            return ((m_baseColorTexture == null)
                        == false);
        }

        public bool ShouldSerializeMetallicFactor()
        {
            return ((m_metallicFactor == 1F)
                        == false);
        }

        public bool ShouldSerializeRoughnessFactor()
        {
            return ((m_roughnessFactor == 1F)
                        == false);
        }

        public bool ShouldSerializeMetallicRoughnessTexture()
        {
            return ((m_metallicRoughnessTexture == null)
                        == false);
        }

        public bool ShouldSerializeExtensions()
        {
            return ((m_extensions == null)
                        == false);
        }

        public bool ShouldSerializeExtras()
        {
            return ((m_extras == null)
                        == false);
        }
    }
}
